name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/cornix.keymap"
      - "boards/jzf/cornix/cornix.dtsi"
      - "keymap_drawer/config.yaml"
      - "keymap_drawer/combos.yaml"
      - ".github/workflows/draw-zmk.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      install_branch: "dev"
      keymap_patterns: "config/cornix.keymap"
      config_path: "keymap_drawer/config.yaml"
      output_folder: "keymap_drawer"
      parse_args: ""
      draw_args: ""
      fail_on_error: true
